[package]
name = "async-http-codec"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.5"
httparse = "1.5.1"
futures-lite = "1.12.0"
anyhow = "1.0.44"
pin-project = "1.0.8"