[package]
name = "async-http-codec"
version = "0.3.0"
edition = "2018"
description = "async HTTP 1.1 encoding and decoding"
license = "Apache-2.0 OR MIT"

[dependencies]
http = "0.2.5"
httparse = "1.5.1"
futures-lite = "1.12.0"
anyhow = "1.0.44"
log = "0.4.14"

[dev-dependencies]
async-net-server-utils = { git = "https://github.com/FlorianUekermann/async-net-server-utils" }
simple_logger = "1.13.0"